# Generated by Django 2.1.7 on 2019-12-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Done_Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Tên khách hàng')),
                ('number_phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('order_list', models.TextField(verbose_name='Danh sách đặt hàng')),
                ('description', models.TextField(verbose_name='Ghi chú')),
                ('check_order', models.BooleanField(default=False)),
                ('person_check', models.CharField(max_length=20, verbose_name='Người check')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Tên')),
                ('amount', models.IntegerField(verbose_name='Số lượng')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('price', models.IntegerField(verbose_name='Giá')),
                ('type', models.CharField(max_length=20, verbose_name='Loại')),
            ],
        ),
        migrations.AddField(
            model_name='done_delivery',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vanhanh.Order'),
        ),
    ]
