# Generated by Django 2.1.7 on 2019-12-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vanhanh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typeproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Loại sản phẩm')),
                ('highlight', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='done_delivery',
            name='date_done',
            field=models.DateField(null=True, verbose_name='Ngày giao'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(max_length=50, null=True, verbose_name='Tên đơn hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Giá đơn hàng'),
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.CharField(max_length=50, null=True, verbose_name='Thương hiệu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vanhanh.Typeproduct'),
        ),
    ]
