# Generated by Django 2.1.7 on 2019-12-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanhanh', '0002_auto_20191227_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='highlight',
            field=models.BooleanField(default=False, verbose_name='Nổi bật tại trang chủ'),
        ),
    ]
