# Generated by Django 2.1.7 on 2019-12-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanhanh', '0004_auto_20191227_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_off',
            field=models.IntegerField(null=True, verbose_name='Giá giảm'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale',
            field=models.CharField(max_length=50, null=True, verbose_name='Giá bán sĩ'),
        ),
    ]
