# Generated by Django 3.0.1 on 2019-12-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanhanh', '0006_auto_20191227_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
    ]
