# Generated by Django 2.1.7 on 2019-12-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanhanh', '0007_auto_20191227_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Thương hiệu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='4.jpg', null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=150000, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale',
            field=models.CharField(default='150k/cái', max_length=50, null=True, verbose_name='Giá bán sĩ'),
        ),
    ]
