# Generated by Django 2.1.7 on 2020-01-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanhanh', '0008_auto_20191229_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nofication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email khách hàng')),
            ],
            options={
                'verbose_name': 'Nofication',
                'verbose_name_plural': 'Email khách hàng',
            },
        ),
        migrations.AlterModelOptions(
            name='done_delivery',
            options={'verbose_name': 'Done_Delivery', 'verbose_name_plural': 'Đơn hàng đã hoàn thành'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='typeproduct',
            options={'verbose_name': 'Typeproduct', 'verbose_name_plural': 'Loại sản phẩm'},
        ),
    ]
