# Generated by Django 2.1.7 on 2020-01-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vanhanh', '0009_auto_20200104_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grouptype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Loại chung')),
                ('highlight', models.BooleanField(default=True, verbose_name='Hiển thị title')),
            ],
            options={
                'verbose_name': 'Grouptype',
                'verbose_name_plural': 'Nhóm sản phẩm',
            },
        ),
        migrations.AddField(
            model_name='typeproduct',
            name='group_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vanhanh.Grouptype'),
        ),
    ]
