# Generated by Django 3.0.2 on 2020-01-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vanhanh', '0010_auto_20200104_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(max_length=50, verbose_name='Tên đơn hàng')),
                ('name', models.CharField(max_length=50, verbose_name='Tên khách hàng')),
                ('number_phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('price', models.CharField(max_length=20, null=True, verbose_name='Giá đơn hàng')),
                ('order_list', models.TextField(verbose_name='Danh sách đặt hàng')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('check_order', models.BooleanField(default=False)),
                ('person_check', models.CharField(blank=True, max_length=20, null=True, verbose_name='Người check')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Đơn hàng',
            },
        ),
        migrations.AlterField(
            model_name='done_delivery',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vanhanh.Delivery'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
