# Generated by Django 3.0.2 on 2020-03-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanhanh', '0011_auto_20200114_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeproduct',
            name='list_show',
            field=models.BooleanField(default=False, verbose_name='Hiển thị ở trang chủ'),
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='highlight',
            field=models.BooleanField(default=False, verbose_name='Sản phẩm bán chạy'),
        ),
    ]
